language: python
sudo: required
python:
  - 3.6
  - "3.7"
# Install python 3.7, Travis does not have it
install:
  - echo "Installing python 3.7"
  - sudo apt-get update
  - wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
  - tar -xf Python-3.7.3.tar.xz
  - cd Python-3.7.3
  - ./configure -q --enable-optimizations --with-ensurepip=install
  - make -j 8
  - sudo make altinstall
  - virtualenv -p python3.7 test-barseq
  - source ~/venv/test-barseq/bin/activate
  - pip install -r requirements.txt
script:
  - make test
after_success:
  - codecov
notifications:
  email:
    recipients:
      - eburgos@wisc.edu